---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./route.yaml
commonLabels:
  app: $APPLICATION_NAME-$SERVICE_NAME
  app.kubernetes.io/name: $APPLICATION_NAME-$SERVICE_NAME
  app.kubernetes.io/component: $APPLICATION_NAME-$SERVICE_NAME
  app.kubernetes.io/instance: $APPLICATION_NAME-$SERVICE_NAME
  app.kubernetes.io/part-of: $APPLICATION_NAME-$SERVICE_NAME
