---
apiVersion: v1
kind: Secret
metadata:
  name: git-auth-$APPLICATION_NAME-$SERVICE_NAME
  namespace: $NAMESPACE
  annotations:
    tekton.dev/git-0: $GIT_SERVER_DOMAIN
type: kubernetes.io/basic-auth
stringData:
  username: $GIT_USER
  password: $GIT_ACCESS_TOKEN
