---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-trigger-bot
  namespace: $NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-trigger-bot
subjects:
  - kind: ServiceAccount
    name: pipeline-trigger-bot
    namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-trigger-bot
subjects:
  - kind: ServiceAccount
    name: pipeline-trigger-bot
    namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles