---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-bot
  namespace: $NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  deployment-bot
  namespace: $NAMESPACE
rules:
  - verbs:
      - get
      - create
      - list
      - patch
      - watch
    apiGroups:
      - route.openshift.io
      - apps
      - ''
    resources:
      - deployments
      - routes
      - services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-bot
  namespace: $NAMESPACE
subjects:
  - kind: ServiceAccount
    name: deployment-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-bot