---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-bot
  namespace: $NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-bot
  namespace: $NAMESPACE
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-bot
  namespace: $NAMESPACE
subjects:
  - kind: ServiceAccount
    name: git-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-bot-read-secrets
