---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: git-webhook-$APPLICATION_NAME-$SERVICE_NAME
  namespace: $NAMESPACE
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-$APPLICATION_NAME-$SERVICE_NAME
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
