apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-deployment
spec:
  params:
    - name: app-namespace
      description: namespace for the deployment
    - name: app-name
      description: the name of the app
  workspaces:
    - name: source
      description: contains the cloned git repo
  results:
    - name: service-port
    - name: resource-type
  steps:
    - name: deploy
      image: registry.redhat.io/openshift4/ose-cli
      script: |
        #!/bin/sh
        cd source
        set -e
        APP_NAMESPACE="$(params.app-namespace)"
        echo -e "Deploying into: ${APP_NAMESPACE}"
        oc apply -n ${APP_NAMESPACE} -f ./k8s/manifests.yaml --validate=false > results.out
        cat results.out
    - name: verify-deploy
      image: registry.redhat.io/openshift4/ose-cli
      script: |
        #!/bin/sh
        cd source
        set -e
        APP_NAMESPACE="$(params.app-namespace)"
        APP_NAME="$(params.app-name)"
        cat results.out | \
          grep -E "deployment|statefulset|integrationserver|queuemanager" | \
          sed "s/deployment.apps/deployment/g" | \
          sed "s/statefulset.apps/statefulset/g" | \
          sed "s/configured//g" | \
          sed "s/created//g" | \
          sed "s/unchanged//g" | while read target; do
            echo "Waiting for rollout of ${target} in ${APP_NAMESPACE}"
            oc rollout status -n ${APP_NAMESPACE} ${target}
          done
